#ifndef TEST_DEMO_CORE2_GLOBAL_H
#define TEST_DEMO_CORE2_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TEST_DEMO_CORE2_LIB
# define TEST_DEMO_CORE2_EXPORT Q_DECL_EXPORT
#else
# define TEST_DEMO_CORE2_EXPORT Q_DECL_IMPORT
#endif

#endif // TEST_DEMO_CORE2_GLOBAL_H
